name: 部屬PM2 專案

on:
  push:
    branches:
      - feature/action-pm2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install, build
        run: |
          npm install

      - name: Create .env file
        run: |
          echo ENV_VARIALBES=${{ secrets.ENV_VARIALBES }} >> .env
          echo PORT=${{ secrets.ENV_PORT }} >> .env

      - name: Install SSH key # 第二步，安裝 SSH 密鑰
        uses: webfactory/ssh-agent@v0.5.3 # 使用第三方的 ssh-agent 動作
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }} # 從 GitHub Secrets 中取得私鑰

      - name: 更新 known_hosts 文件 # 步驟的名稱
        run: | # 將要執行的命令
          mkdir -p ~/.ssh
          ssh-keyscan 172.234.95.61 >> ~/.ssh/known_hosts

      - name: Transfer files # 第六步，傳輸文件
        run:
          rsync -avz --delete ./ root@172.234.95.61:~/website-sample/action-test/ # 使用 rsync 命令將文件傳輸到虛擬主機
          # root@hostname 請替換成相應的帳號及主機位置(ip 或網址)
        env:
          ENV_VARIABLE: ${{ secrets.ENV_VARIABLE }} # 從 GitHub Secrets 中取得環境變數的值

      - name: Restart PM2 # 第八步，重啟 PM2
        run: ssh root@172.234.95.61 'cd ~/website-sample/action-test/ && pm2 restart www --update-env' # 透過 SSH 連到虛擬主機，然後進到應用程式的目錄，並重啟所有 PM2 管理的應用程式
