name: 部屬PM2 專案

on:
  push:
    branches:
      - feature/action-pm2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      -name : checkout defalut env
        run: env